services:
  - type: web
    name: your-bot-service
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn your_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yourdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    plan: free