# Generated by Django 5.1.7 on 2025-03-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('from_address', models.TextField()),
                ('to_address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('package_type', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='orders/')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтвержден'), ('delivered', 'Доставлен')], default='pending', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
