# Generated by Django 5.1.7 on 2025-04-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_order_client_feedback_order_courier_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Оценка от 1 до 5', null=True, verbose_name='Оценка клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтвержден'), ('paid', 'Оплачен'), ('assigned', 'Назначен курьеру'), ('in_progress', 'В процессе доставки'), ('delivered', 'Доставлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
